### ISSUE TITLE
treepy-list-zip doesn't support dotted lists

### ISSUE THREAD

**Issue by tarsius** [volrath/treepy.el#3]
`treepy-list-zip` fails on dotted lists:

```lisp
(thread-last (treepy-list-zip '(a b . c))
  treepy-next
  treepy-next
  treepy-next)
```

```
Debugger entered--Lisp error: (wrong-type-argument sequencep c)
  seq-length(c)
  #f(compiled-function (sequence n) #<bytecode 0x147fe5d>)(c 1)
  apply(#f(compiled-function (sequence n) #<bytecode 0x147fe5d>) c 1)
  seq-drop(c 1)
  treepy-right(((b (:l a) (:pnodes (a b . c)) (:ppath) (:r . c)) (:branchp . listp) (:children . identity) (:make-node . #f(compiled-function (_ children) #<bytecode 0x16b60a9>))))
  treepy--preorder-next(((b (:l a) (:pnodes (a b . c)) (:ppath) (:r . c)) (:branchp . listp) (:children . identity) (:make-node . #f(compiled-function (_ children) #<bytecode 0x16b60a9>))))
  treepy-next(((b (:l a) (:pnodes (a b . c)) (:ppath) (:r . c)) (:branchp . listp) (:children . identity) (:make-node . #f(compiled-function (_ children) #<bytecode 0x16b60a9>))))
```

I don't know what the correct solution is here. Maybe it okay to just fail when running into dotted lists.

But there is one special case that I think `treepy` should handle; alists whose elements have atoms as values, such as `((var . val) (foo . bar))`. Please consider adding an additional `treepy-alist-zip`, unless you can come up with something better:

```lisp
(defun treepy-alist-zip (root)
  "Return a zipper for nested lists, given a ROOT list.
Unlike `treepy-list-zip', this also supports alists whose
elements have atoms as values.."
  (let ((branchp (lambda (elt) (and (listp elt) (listp (cdr elt)))))
	(make-node (lambda (_ children) children)))
    (treepy-zipper branchp #'identity make-node root)))
```

**Comment by tarsius** [comment]
(Of course that might not always be the right thing to do, as one might want to actually visit a key and its value separately. As I said, unless you can come up with something better...)

**Comment by volrath** [comment]
Thanks for opening the issue.

I took a look at these [non-nil final cdr](https://www.gnu.org/software/emacs/manual/html_node/elisp/Dotted-Pair-Notation.html) type of lists and I think we should definitely handle those.

The problem currently lies when iterating over the "rights" of the location, we use `seq-let` to destructure these rights sequence, and this fails with the last element cause it's not a `sequence` (`(cons 'c nil)`) but just a single element `c`.

I'm going to think a bit more about what would be the best solution and probably push an implementation by the end of the day.

Re. implementing a zipper for alists, the thing is that (as you correctly pointed out) there are multiple ways to handle those. Because of this, I'd prefer to leave these zipper implementations to the users of the library instead of trying to cover one (or all) specific use cases.  Hope this makes sense.

**Comment by volrath** [comment]
@tarsius feel free to take a look at #4, I added a test case that covers the point first point you raised in this issue.  I plan to merge it tomorrow.
